---
title: "MetaNetX Reactions Summary"
author: "Moritz E. Beber"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
params:
  reac_prop: metanetx-nf/results/mnx-4.2-processed/processed_reac_prop.tsv
  reac_xref: metanetx-nf/results/mnx-4.2-processed/processed_reac_xref.tsv
  reac_depr: metanetx-nf/results/mnx-4.2-processed/processed_reac_depr.tsv
---

___

## Intro

A summary of the raw tables downloaded from MetaNetX.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
options(knitr.kable.NA = "")
```

```{r dependencies, include=FALSE}
requireNamespace("readr")
requireNamespace("dplyr")
requireNamespace("tidyr")
requireNamespace("knitr")
requireNamespace("forcats")
requireNamespace("ggplot2")
requireNamespace("ggforce")
`%>%` <- dplyr::`%>%`
```

```{r extract-reaction, include=FALSE, cache=TRUE}
reac_prop <- readr::read_tsv(params$reac_prop)
reac_xref <- readr::read_tsv(params$reac_xref)
reac_depr <- readr::read_tsv(params$reac_depr)
```

## Properties

```{r, include=FALSE}
numbers <- reac_prop %>%
  dplyr::summarise(
    num_reacs = dplyr::n_distinct(mnx_id[!is.na(mnx_id)]),
    num_ec = length(ec_number[!is.na(ec_number)]),
    num_balanced = length(is_balanced[!is.na(is_balanced)]),
    num_trans = length(is_transport[!is.na(is_transport)]),
    num_namespaces = dplyr::n_distinct(prefix[!is.na(prefix)])
  )
```

```{r, results='asis'}
numbers %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of Reactions",
      "with EC number",
      "balanced",
      "transport",
      "Number of Namespaces"
    ),
    caption = "The number of reactions and sources for them in MetaNetX."
  )
```

```{r, results='asis'}
numbers %>%
  dplyr::select(-num_namespaces) %>%
  dplyr::mutate(
    dplyr::across(.fns = ~ .x / !!(numbers$num_reacs)),
    dplyr::across(.fns = ~ scales::percent(.x, accuracy = 0.01))
  ) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Percent of Reactions",
      "with EC number",
      "balanced",
      "transport"
    ),
    caption = "The percentage of reactions with information in MetaNetX."
  )
```

```{r, results='asis'}
reac_prop %>%
  dplyr::select(prefix) %>%
  dplyr::count(prefix) %>%
  dplyr::arrange(prefix) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c("Namespace", "Frequency"),
    caption = "The source namespaces from which reactions are included in MetaNetX."
  )
```

## Cross-References

```{r, results='asis'}
reac_xref %>%
  dplyr::summarise(
    num_reacs = dplyr::n_distinct(mnx_id[!is.na(mnx_id)]),
    num_namespaces = dplyr::n_distinct(prefix[!is.na(prefix)])
  ) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of reactions",
      "Number of Namespaces"
    ),
    caption = "reactions with cross-references to other databases."
  )
```

```{r, results='asis'}
reac_xref %>%
  dplyr::select(prefix) %>%
  dplyr::count(prefix) %>%
  dplyr::arrange(prefix) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c("Namespace", "Frequency"),
    caption = "The namespaces to which cross-references from MetaNetX are established."
  )
```

```{r, fig.align='center', dpi=300, fig.cap='Number of namespaces and cross-references per reaction in MetaNetX.'}
reac_xref %>%
  dplyr::group_by(mnx_id) %>%
  dplyr::summarise(
    num_xref = dplyr::n_distinct(identifier[!is.na(identifier)]),
    num_prefix = dplyr::n_distinct(prefix[!is.na(prefix)])
  ) %>%
  dplyr::ungroup() %>%
  tidyr::pivot_longer(!mnx_id) %>%
  dplyr::mutate(
    name = forcats::fct_recode(name,
      "Namespaces" = "num_prefix",
      "Cross-References" = "num_xref"
    )
  ) %>%
  ggplot2::ggplot(ggplot2::aes(x = name, y = value)) +
  ggplot2::geom_boxplot(show.legend = FALSE) +
  ggplot2::geom_violin(scale = "width", alpha = 0, show.legend = FALSE) +
  ggplot2::scale_y_log10() +
  ggplot2::xlab(NULL) +
  ggplot2::ylab("Number")
```

## Deprecated MetaNetX Identifiers

```{r, results='asis'}
reac_depr %>%
  dplyr::summarise(
    num_reacs = dplyr::n_distinct(current_id[!is.na(current_id)]),
    num_deprecated = dplyr::n_distinct(deprecated_id[!is.na(deprecated_id)]),
  ) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of Reactions",
      "Number of Deprecated Identifiers"
    ),
    caption = "The total number of reactions and how many deprecated identifiers there are."
  )
```

```{r, fig.align='center', dpi=300, fig.cap='Number of deprecated MNX identifiers per reaction.'}
if (nrow(reac_depr) > 0) {
  reac_depr %>%
    dplyr::group_by(current_id) %>%
    dplyr::summarise(
      num_depr = dplyr::n_distinct(deprecated_id[!is.na(deprecated_id)]),
    ) %>%
    dplyr::ungroup() %>%
    ggplot2::ggplot(ggplot2::aes(x = "Deprecated", y = num_depr)) +
    ggplot2::geom_boxplot(show.legend = FALSE) +
    ggplot2::geom_violin(scale = "width", alpha = 0, show.legend = FALSE) +
    ggplot2::scale_y_log10() +
    ggplot2::xlab(NULL) +
    ggplot2::ylab("Number")
}
```
