---
title: "Reduced Set Summary"
author: "Moritz E. Beber"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: 3
params:
  database: "../metanetx.sqlite"
---

___

## Intro

The entire, normalized database of compartments, compounds, and reactions at 2.6 GB is larger than what many people are used to. We are interested in creating a reduced set to distribute by default.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
options(knitr.kable.NA = "")
```

```{r dependencies, include=FALSE}
requireNamespace("DBI")
requireNamespace("RSQLite")
requireNamespace("dbplyr")
requireNamespace("dplyr")
requireNamespace("tidyr")
requireNamespace("knitr")
requireNamespace("forcats")
requireNamespace("scales")
requireNamespace("ggplot2")
`%>%` <- dplyr::`%>%`
```

```{r scripts, include=FALSE}
source("scripts/db_helpers.R")
source("scripts/venn.R")
```

```{r, include=FALSE}
con <- DBI::dbConnect(RSQLite::SQLite(), params$database)
```

```{r extract-chemical, include=FALSE}
compounds <- dplyr::tbl(con, "compounds")
participants <- dplyr::tbl(con, "participants")
compound_annotations <- dplyr::tbl(con, "compound_annotations")
compound_names <- dplyr::tbl(con, "compound_names")
namespaces <- dplyr::tbl(con, "namespaces")
```

```{r, include=FALSE}
reduced <- compounds %>%
  dplyr::inner_join(
    participants %>%
      dplyr::select(compound_id) %>%
      dplyr::distinct(compound_id),
    by = c("id" = "compound_id")
  )
```

```{r, include=FALSE}
annotations <- reduced %>%
  dplyr::select(id) %>%
  dplyr::left_join(
    compound_annotations %>%
      dplyr::select(compound_id, identifier, is_deprecated, namespace_id),
    by = c("id" = "compound_id")
  ) %>%
  dplyr::left_join(
    namespaces %>%
      dplyr::select(id, prefix),
    by = c("namespace_id" = "id")
  ) %>%
  dplyr::select(id, prefix, identifier, is_deprecated)
```

```{r include=FALSE}
names <- reduced %>%
  dplyr::select(id) %>%
  dplyr::left_join(
    compound_names %>%
      dplyr::select(compound_id, name, namespace_id),
    by = c("id" = "compound_id")
  ) %>%
  dplyr::left_join(
    namespaces %>%
      dplyr::select(id, prefix),
    by = c("namespace_id" = "id")
  ) %>%
  dplyr::select(id, prefix, name)
```

## Properties

```{r, include=FALSE}
numbers <- reduced %>%
  dplyr::summarise(
    num_chems = COUNT(id),
    num_formula = COUNT(chemical_formula),
    num_charge = COUNT(charge),
    num_smiles = COUNT(smiles),
    num_mass = COUNT(mass),
    num_inchi = COUNT(inchi),
    num_inchi_key = COUNT(inchi_key)
  ) %>%
  dplyr::collect()
```


```{r, results='asis'}
numbers %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of Chemicals",
      "with formula",
      "with charge",
      "with SMILES",
      "with mass",
      "with InChI",
      "with InChIKey"
    ),
    caption = "The number of chemicals that participate in any recorded reaction and their properties."
  )
```

```{r, results='asis'}
numbers %>%
  dplyr::mutate(
    dplyr::across(.fns = ~ .x / !!(numbers$num_chems)),
    dplyr::across(.fns = ~ scales::percent(.x, accuracy = 0.01))
  ) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Percent of Chemicals",
      "with formula",
      "with charge",
      "with SMILES",
      "with mass",
      "with InChI",
      "with InChIKey"
    ),
    caption = "The percentage of chemical information in MetaNetX."
  )
```

```{r, results='hide', fig.align='center', dpi=300, fig.cap='Venn diagram of structural annotation and mass.'}
reduced %>%
  dplyr::rename(formula = chemical_formula) %>%
  plot_venn_mass(id)
```

```{r, results='hide', fig.align='center', dpi=300, fig.cap='Venn diagram of structural annotation and electric charge.'}
reduced %>%
  dplyr::rename(formula = chemical_formula) %>%
  plot_venn_charge(id)
```

```{r, results='asis'}
summarize_formula(reduced, chemical_formula) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of Formulae",
      "with `*`",
      "with `R`",
      "with `Z[z]`"
    ),
    caption = "Chemical formulae that are not fully determined."
  )
```

```{r, results='asis'}
summarize_formula(reduced, smiles) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of SMILES",
      "with `*`",
      "with `R`",
      "with `Z[z]`"
    ),
    caption = "SMILES that are not fully determined."
  )
```

```{r, results='asis'}
summarize_inchi(reduced) %>%
  knitr::kable(
    format.args = list(big.mark = ","),
    col.names = c(
      "Number of InChIs",
      "with `*`",
      "with `R`",
      "with `Z[z]`"
    ),
    caption = "InChIs that are not fully determined."
  )
```

## Annotation

```{r, results='asis'}
annotations %>% summarize_annotation()
```

```{r, results='asis'}
annotations %>% summarize_annotation_sources()
```

```{r, include=FALSE}
ann_per_compound <- annotations %>% annotation_per_element()
```

```{r, fig.align='center', dpi=300, fig.cap='The empirical cumulative distribution function (eCDF) of the number of distinct identifiers per compound.'}
ann_per_compound %>%
  ggplot2::ggplot(ggplot2::aes(x = num_ann)) +
  ggplot2::stat_ecdf() +
  ggplot2::xlab("Number of Identifiers per Compound") +
  ggplot2::ylab("Cumulative Probability")
```

```{r, fig.align='center', dpi=300, fig.cap='The number of distinct identifiers per compound and the number of unique source namespaces per compound. Only compounds that have more than two identifiers are included.'}
ann_per_compound %>%
  dplyr::filter(num_ann > 2) %>%
  plot_annotation()
```

## Names

```{r, results='asis'}
names %>% summarize_names()
```

```{r, results='asis'}
names %>% summarize_name_sources()
```

```{r, include=FALSE}
names_per_compound <- names %>% name_per_element()
```

```{r, fig.align='center', dpi=300, fig.cap='The empirical cumulative distribution function (eCDF) of the number of distinct names per compound.'}
names_per_compound %>%
  ggplot2::ggplot(ggplot2::aes(x = num_name)) +
  ggplot2::stat_ecdf() +
  ggplot2::xlab("Number of Names per Compound") +
  ggplot2::ylab("Cumulative Probability")
```

```{r, fig.align='center', dpi=300, fig.cap='The number of names per compound and  the number of unique source namespaces per compound. Only compounds that have more than one name are included.'}
names_per_compound %>%
  dplyr::filter(num_name > 1) %>%
  plot_names()
```

```{r, include=FALSE}
DBI::dbDisconnect(con)
```
